import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'en' | 'he' | 'ar' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.menu': 'Menu',
    'nav.admin': 'Admin',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.dashboard': 'Dashboard',
    'menu.title': 'Our Menu',
    'menu.subtitle': 'Discover our carefully crafted selection',
    'menu.currency': '₪',
    'menu.noItems': 'No items available',
    'menu.viewMenu': 'View Menu',
    'hero.title': 'Cafe Nof',
    'hero.subtitle': 'Karmiel',
    'hero.description': 'Experience the finest coffee and pastries in a warm, welcoming atmosphere',
    'admin.title': 'Admin Dashboard',
    'admin.categories': 'Categories',
    'admin.items': 'Menu Items',
    'admin.aiChat': 'AI Assistant',
    'admin.addCategory': 'Add Category',
    'admin.addItem': 'Add Item',
    'admin.edit': 'Edit',
    'admin.delete': 'Delete',
    'admin.save': 'Save',
    'admin.cancel': 'Cancel',
    'admin.confirmDelete': 'Are you sure you want to delete this?',
    'ai.placeholder': 'Type your request in natural language...',
    'ai.send': 'Send',
    'ai.uploadImage': 'Upload Images',
    'ai.processing': 'Processing...',
    'ai.success': 'Changes applied successfully',
    'ai.error': 'Error processing request',
    'ai.welcome': 'Hello! I can help you manage your menu. Try saying things like:',
    'ai.example1': '"Add a new espresso for 12 shekels"',
    'ai.example2': '"Update the price of cappuccino to 15"',
    'ai.example3': '"Create a new category called Smoothies"',
    'auth.login': 'Login',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.loginButton': 'Sign In',
    'auth.error': 'Invalid credentials',
    'auth.adminOnly': 'Admin access only',
    'form.nameEn': 'Name (English)',
    'form.nameHe': 'Name (Hebrew)',
    'form.nameAr': 'Name (Arabic)',
    'form.nameRu': 'Name (Russian)',
    'form.descriptionEn': 'Description (English)',
    'form.descriptionHe': 'Description (Hebrew)',
    'form.descriptionAr': 'Description (Arabic)',
    'form.descriptionRu': 'Description (Russian)',
    'form.price': 'Price',
    'form.category': 'Category',
    'form.image': 'Image',
    'form.active': 'Active',
    'form.costPrice': 'Cost Price',
    'form.sortOrder': 'Sort Order',
    // Waiter
    'waiter.selectTable': 'Select a table to begin',
    'waiter.table': 'Table',
    'waiter.searchMenu': 'Search menu...',
    'waiter.noItemsFound': 'No items found',
    'waiter.noItemsYet': 'No items yet',
    'waiter.tapToAdd': 'Tap products to add them',
    'waiter.sendOrder': 'Send Order',
    'waiter.total': 'Total',
    'waiter.items': 'items',
    'waiter.clearAll': 'Clear All',
    'waiter.addNote': 'Add note',
    'waiter.editNote': 'Edit note',
    'waiter.specialRequests': 'Special requests...',
    'waiter.viewOrder': 'View Order',
    'waiter.all': 'All',
    'waiter.selectItems': 'Select items to order',
    'waiter.free': 'Free',
    'waiter.active': 'Active',
    'waiter.served': 'Served',
    'waiter.preparing': 'Preparing',
    'waiter.logout': 'Logout',
    'waiter.activeOrders': 'Active Orders',
    'waiter.noActiveOrders': 'No active orders for this table',
    'waiter.tableCount': 'Number of Tables',
    'waiter.settings': 'Settings',
    'waiter.newOrder': 'New',
    'waiter.tableActivity': 'Table Activity',
    'waiter.orderFor': 'Order for',
    'waiter.markPaid': 'Mark as Paid',
    'waiter.readyBadge': 'Ready!',
    'waiter.addItems': 'Add Items',
    'waiter.payNow': 'Pay & Close Table',
    'waiter.outstanding': 'Outstanding',
    'waiter.waitingPayment': 'Waiting for payment',
    'waiter.tableDetails': 'Table Details',
    'waiter.servedOrders': 'Ready orders',
    'waiter.paidSuccess': 'Payment recorded!',
    'waiter.selectPayment': 'Select Payment Method',
    'waiter.cash': 'Cash',
    'waiter.credit': 'Credit Card',
    'waiter.appPay': 'App / Transfer',
    'waiter.other': 'Other',
    'waiter.paymentNote': 'Note (optional)...',
    'waiter.confirmPayment': 'Confirm Payment',
    // Kitchen
    'kitchen.title': 'Kitchen Display',
    'kitchen.new': 'New',
    'kitchen.preparing': 'Preparing',
    'kitchen.ready': 'Ready',
    'kitchen.startPreparing': 'Start Preparing',
    'kitchen.markReady': 'Mark Ready',
    'kitchen.min': 'min',
    'kitchen.live': 'Live',
    'kitchen.offline': 'Offline',
    'kitchen.noNewOrders': 'No new orders',
    'kitchen.noPreparing': 'Nothing in preparation',
    'kitchen.noReady': 'Nothing ready yet',
    // Inventory
    'admin.inventory': 'Inventory',
    'admin.history': 'History',
    'waiter.addSessionNote': 'Add customer note...',
    'waiter.sessionNotePlaceholder': 'e.g. Allergy: nuts, Birthday, VIP...',
  },
  he: {
    'nav.menu': 'תפריט',
    'nav.admin': 'ניהול',
    'nav.login': 'התחברות',
    'nav.logout': 'התנתקות',
    'nav.dashboard': 'לוח בקרה',
    'menu.title': 'התפריט שלנו',
    'menu.subtitle': 'גלו את המבחר המוקפד שלנו',
    'menu.currency': '₪',
    'menu.noItems': 'אין פריטים זמינים',
    'menu.viewMenu': 'צפה בתפריט',
    'hero.title': 'קפה נוף',
    'hero.subtitle': 'כרמיאל',
    'hero.description': 'חוו את הקפה והמאפים המשובחים ביותר באווירה חמה ומזמינה',
    'admin.title': 'לוח ניהול',
    'admin.categories': 'קטגוריות',
    'admin.items': 'פריטי תפריט',
    'admin.aiChat': 'עוזר AI',
    'admin.addCategory': 'הוסף קטגוריה',
    'admin.addItem': 'הוסף פריט',
    'admin.edit': 'ערוך',
    'admin.delete': 'מחק',
    'admin.save': 'שמור',
    'admin.cancel': 'ביטול',
    'admin.confirmDelete': 'האם אתה בטוח שברצונך למחוק?',
    'ai.placeholder': 'הקלד את הבקשה שלך בשפה טבעית...',
    'ai.send': 'שלח',
    'ai.uploadImage': 'העלה תמונות',
    'ai.processing': 'מעבד...',
    'ai.success': 'השינויים בוצעו בהצלחה',
    'ai.error': 'שגיאה בעיבוד הבקשה',
    'ai.welcome': 'שלום! אני יכול לעזור לך לנהל את התפריט. נסה לומר דברים כמו:',
    'ai.example1': '"הוסף אספרסו חדש ב-12 שקלים"',
    'ai.example2': '"עדכן את המחיר של קפוצ\'ינו ל-15"',
    'ai.example3': '"צור קטגוריה חדשה בשם שייקים"',
    'auth.login': 'התחברות',
    'auth.email': 'אימייל',
    'auth.password': 'סיסמה',
    'auth.loginButton': 'התחבר',
    'auth.error': 'פרטים שגויים',
    'auth.adminOnly': 'גישה למנהלים בלבד',
    'form.nameEn': 'שם (אנגלית)',
    'form.nameHe': 'שם (עברית)',
    'form.nameAr': 'שם (ערבית)',
    'form.nameRu': 'שם (רוסית)',
    'form.descriptionEn': 'תיאור (אנגלית)',
    'form.descriptionHe': 'תיאור (עברית)',
    'form.descriptionAr': 'תיאור (ערבית)',
    'form.descriptionRu': 'תיאור (רוסית)',
    'form.price': 'מחיר',
    'form.category': 'קטגוריה',
    'form.image': 'תמונה',
    'form.active': 'פעיל',
    'form.costPrice': 'מחיר עלות',
    'form.sortOrder': 'סדר מיון',
    // Waiter
    'waiter.selectTable': 'בחר שולחן להתחיל',
    'waiter.table': 'שולחן',
    'waiter.searchMenu': 'חפש בתפריט...',
    'waiter.noItemsFound': 'לא נמצאו פריטים',
    'waiter.noItemsYet': 'אין פריטים עדיין',
    'waiter.tapToAdd': 'הקש על מוצרים להוסיפם',
    'waiter.sendOrder': 'שלח הזמנה',
    'waiter.total': 'סה"כ',
    'waiter.items': 'פריטים',
    'waiter.clearAll': 'נקה הכל',
    'waiter.addNote': 'הוסף הערה',
    'waiter.editNote': 'ערוך הערה',
    'waiter.specialRequests': 'בקשות מיוחדות...',
    'waiter.viewOrder': 'צפה בהזמנה',
    'waiter.all': 'הכל',
    'waiter.selectItems': 'בחר פריטים להזמנה',
    'waiter.free': 'פנוי',
    'waiter.active': 'פעיל',
    'waiter.served': 'הוגש',
    'waiter.preparing': 'בהכנה',
    'waiter.logout': 'התנתק',
    'waiter.activeOrders': 'הזמנות פעילות',
    'waiter.noActiveOrders': 'אין הזמנות פעילות לשולחן זה',
    'waiter.tableCount': 'מספר שולחנות',
    'waiter.settings': 'הגדרות',
    'waiter.newOrder': 'חדש',
    'waiter.tableActivity': 'פעילות שולחן',
    'waiter.orderFor': 'הזמנה עבור',
    'waiter.markPaid': 'סמן כשולם',
    'waiter.readyBadge': 'מוכן!',
    'waiter.addItems': 'הוסף פריטים',
    'waiter.payNow': 'שלם וסגור שולחן',
    'waiter.outstanding': 'יתרה לתשלום',
    'waiter.waitingPayment': 'ממתין לתשלום',
    'waiter.tableDetails': 'פרטי שולחן',
    'waiter.servedOrders': 'הזמנות מוכנות',
    'waiter.paidSuccess': 'התשלום נרשם!',
    'waiter.selectPayment': 'בחר אמצעי תשלום',
    'waiter.cash': 'מזומן',
    'waiter.credit': 'כרטיס אשראי',
    'waiter.appPay': 'אפליקציה / העברה',
    'waiter.other': 'אחר',
    'waiter.paymentNote': 'הערה (אופציונלי)...',
    'waiter.confirmPayment': 'אשר תשלום',
    // Kitchen
    'kitchen.title': 'מסך מטבח',
    'kitchen.new': 'חדש',
    'kitchen.preparing': 'בהכנה',
    'kitchen.ready': 'מוכן',
    'kitchen.startPreparing': 'התחל הכנה',
    'kitchen.markReady': 'סמן כמוכן',
    'kitchen.min': 'דק׳',
    'kitchen.live': 'חי',
    'kitchen.offline': 'לא מחובר',
    'kitchen.noNewOrders': 'אין הזמנות חדשות',
    'kitchen.noPreparing': 'אין בהכנה',
    'kitchen.noReady': 'אין מוכן עדיין',
    // Inventory
    'admin.inventory': 'מלאי',
    'admin.history': 'היסטוריה',
    'waiter.addSessionNote': 'הוסף הערת לקוח...',
    'waiter.sessionNotePlaceholder': 'לדוגמה: אלרגיה לאגוזים, יום הולדת, VIP...',
  },
  ar: {
    'nav.menu': 'القائمة',
    'nav.admin': 'الإدارة',
    'nav.login': 'تسجيل الدخول',
    'nav.logout': 'تسجيل الخروج',
    'nav.dashboard': 'لوحة التحكم',
    'menu.title': 'قائمتنا',
    'menu.subtitle': 'اكتشف تشكيلتنا المختارة بعناية',
    'menu.currency': '₪',
    'menu.noItems': 'لا توجد عناصر متاحة',
    'menu.viewMenu': 'عرض القائمة',
    'hero.title': 'كافيه نوف',
    'hero.subtitle': 'كرميئيل',
    'hero.description': 'استمتع بأفضل القهوة والمعجنات في أجواء دافئة ومرحبة',
    'admin.title': 'لوحة الإدارة',
    'admin.categories': 'الفئات',
    'admin.items': 'عناصر القائمة',
    'admin.aiChat': 'مساعد الذكاء الاصطناعي',
    'admin.addCategory': 'إضافة فئة',
    'admin.addItem': 'إضافة عنصر',
    'admin.edit': 'تعديل',
    'admin.delete': 'حذف',
    'admin.save': 'حفظ',
    'admin.cancel': 'إلغاء',
    'admin.confirmDelete': 'هل أنت متأكد أنك تريد الحذف؟',
    'ai.placeholder': 'اكتب طلبك بلغة طبيعية...',
    'ai.send': 'إرسال',
    'ai.uploadImage': 'تحميل الصور',
    'ai.processing': 'جاري المعالجة...',
    'ai.success': 'تم تطبيق التغييرات بنجاح',
    'ai.error': 'خطأ في معالجة الطلب',
    'ai.welcome': 'مرحباً! يمكنني مساعدتك في إدارة القائمة. جرب قول أشياء مثل:',
    'ai.example1': '"أضف إسبريسو جديد بـ 12 شيكل"',
    'ai.example2': '"حدّث سعر الكابتشينو إلى 15"',
    'ai.example3': '"أنشئ فئة جديدة باسم سموذي"',
    'auth.login': 'تسجيل الدخول',
    'auth.email': 'البريد الإلكتروني',
    'auth.password': 'كلمة المرور',
    'auth.loginButton': 'دخول',
    'auth.error': 'بيانات غير صحيحة',
    'auth.adminOnly': 'للمدراء فقط',
    'form.nameEn': 'الاسم (إنجليزي)',
    'form.nameHe': 'الاسم (عبري)',
    'form.nameAr': 'الاسم (عربي)',
    'form.nameRu': 'الاسم (روسي)',
    'form.descriptionEn': 'الوصف (إنجليزي)',
    'form.descriptionHe': 'الوصف (عبري)',
    'form.descriptionAr': 'الوصف (عربي)',
    'form.descriptionRu': 'الوصف (روسي)',
    'form.price': 'السعر',
    'form.category': 'الفئة',
    'form.image': 'الصورة',
    'form.active': 'نشط',
    'form.costPrice': 'سعر التكلفة',
    'form.sortOrder': 'ترتيب الفرز',
    // Waiter
    'waiter.selectTable': 'اختر طاولة للبدء',
    'waiter.table': 'طاولة',
    'waiter.searchMenu': 'ابحث في القائمة...',
    'waiter.noItemsFound': 'لم يتم العثور على عناصر',
    'waiter.noItemsYet': 'لا توجد عناصر بعد',
    'waiter.tapToAdd': 'اضغط على المنتجات لإضافتها',
    'waiter.sendOrder': 'إرسال الطلب',
    'waiter.total': 'الإجمالي',
    'waiter.items': 'عناصر',
    'waiter.clearAll': 'مسح الكل',
    'waiter.addNote': 'إضافة ملاحظة',
    'waiter.editNote': 'تعديل الملاحظة',
    'waiter.specialRequests': 'طلبات خاصة...',
    'waiter.viewOrder': 'عرض الطلب',
    'waiter.all': 'الكل',
    'waiter.selectItems': 'اختر العناصر للطلب',
    'waiter.free': 'مجانية',
    'waiter.active': 'نشطة',
    'waiter.served': 'قُدِّمت',
    'waiter.preparing': 'قيد التحضير',
    'waiter.logout': 'تسجيل الخروج',
    'waiter.activeOrders': 'الطلبات النشطة',
    'waiter.noActiveOrders': 'لا توجد طلبات نشطة لهذه الطاولة',
    'waiter.tableCount': 'عدد الطاولات',
    'waiter.settings': 'الإعدادات',
    'waiter.newOrder': 'جديد',
    'waiter.tableActivity': 'نشاط الطاولة',
    'waiter.orderFor': 'طلب لـ',
    'waiter.markPaid': 'وضع علامة مدفوع',
    'waiter.readyBadge': 'جاهز!',
    'waiter.addItems': 'إضافة عناصر',
    'waiter.payNow': 'دفع وإغلاق الطاولة',
    'waiter.outstanding': 'المبلغ المستحق',
    'waiter.waitingPayment': 'في انتظار الدفع',
    'waiter.tableDetails': 'تفاصيل الطاولة',
    'waiter.servedOrders': 'طلبات جاهزة',
    'waiter.paidSuccess': 'تم تسجيل الدفع!',
    'waiter.selectPayment': 'اختر طريقة الدفع',
    'waiter.cash': 'نقداً',
    'waiter.credit': 'بطاقة ائتمان',
    'waiter.appPay': 'تطبيق / تحويل',
    'waiter.other': 'أخرى',
    'waiter.paymentNote': 'ملاحظة (اختياري)...',
    'waiter.confirmPayment': 'تأكيد الدفع',
    // Kitchen
    'kitchen.title': 'شاشة المطبخ',
    'kitchen.new': 'جديد',
    'kitchen.preparing': 'قيد التحضير',
    'kitchen.ready': 'جاهز',
    'kitchen.startPreparing': 'ابدأ التحضير',
    'kitchen.markReady': 'وضع علامة جاهز',
    'kitchen.min': 'دق',
    'kitchen.live': 'مباشر',
    'kitchen.offline': 'غير متصل',
    'kitchen.noNewOrders': 'لا توجد طلبات جديدة',
    'kitchen.noPreparing': 'لا شيء قيد التحضير',
    'kitchen.noReady': 'لا شيء جاهز بعد',
    // Inventory
    'admin.inventory': 'المخزون',
    'admin.history': 'السجل',
    'waiter.addSessionNote': 'إضافة ملاحظة...',
    'waiter.sessionNotePlaceholder': 'مثال: حساسية من المكسرات، عيد ميلاد...',
  },
  ru: {
    'nav.menu': 'Меню',
    'nav.admin': 'Админ',
    'nav.login': 'Войти',
    'nav.logout': 'Выйти',
    'nav.dashboard': 'Панель управления',
    'menu.title': 'Наше меню',
    'menu.subtitle': 'Откройте для себя наш тщательно подобранный выбор',
    'menu.currency': '₪',
    'menu.noItems': 'Нет доступных позиций',
    'menu.viewMenu': 'Смотреть меню',
    'hero.title': 'Кафе Ноф',
    'hero.subtitle': 'Кармиэль',
    'hero.description': 'Насладитесь лучшим кофе и выпечкой в тёплой, уютной атмосфере',
    'admin.title': 'Панель управления',
    'admin.categories': 'Категории',
    'admin.items': 'Позиции меню',
    'admin.aiChat': 'AI Ассистент',
    'admin.addCategory': 'Добавить категорию',
    'admin.addItem': 'Добавить позицию',
    'admin.edit': 'Редактировать',
    'admin.delete': 'Удалить',
    'admin.save': 'Сохранить',
    'admin.cancel': 'Отмена',
    'admin.confirmDelete': 'Вы уверены, что хотите удалить?',
    'ai.placeholder': 'Введите запрос на естественном языке...',
    'ai.send': 'Отправить',
    'ai.uploadImage': 'Загрузить изображения',
    'ai.processing': 'Обработка...',
    'ai.success': 'Изменения применены успешно',
    'ai.error': 'Ошибка обработки запроса',
    'ai.welcome': 'Привет! Я могу помочь управлять меню. Попробуйте сказать:',
    'ai.example1': '"Добавь новый эспрессо за 12 шекелей"',
    'ai.example2': '"Обнови цену капучино до 15"',
    'ai.example3': '"Создай новую категорию Смузи"',
    'auth.login': 'Вход',
    'auth.email': 'Эл. почта',
    'auth.password': 'Пароль',
    'auth.loginButton': 'Войти',
    'auth.error': 'Неверные данные',
    'auth.adminOnly': 'Только для администраторов',
    'form.nameEn': 'Название (английский)',
    'form.nameHe': 'Название (иврит)',
    'form.nameAr': 'Название (арабский)',
    'form.nameRu': 'Название (русский)',
    'form.descriptionEn': 'Описание (английский)',
    'form.descriptionHe': 'Описание (иврит)',
    'form.descriptionAr': 'Описание (арабский)',
    'form.descriptionRu': 'Описание (русский)',
    'form.price': 'Цена',
    'form.category': 'Категория',
    'form.image': 'Изображение',
    'form.active': 'Активно',
    'form.costPrice': 'Себестоимость',
    'form.sortOrder': 'Порядок сортировки',
    // Waiter
    'waiter.selectTable': 'Выберите стол для начала',
    'waiter.table': 'Стол',
    'waiter.searchMenu': 'Поиск в меню...',
    'waiter.noItemsFound': 'Позиции не найдены',
    'waiter.noItemsYet': 'Позиций нет',
    'waiter.tapToAdd': 'Нажмите на товары для добавления',
    'waiter.sendOrder': 'Отправить заказ',
    'waiter.total': 'Итого',
    'waiter.items': 'позиций',
    'waiter.clearAll': 'Очистить',
    'waiter.addNote': 'Добавить заметку',
    'waiter.editNote': 'Редактировать',
    'waiter.specialRequests': 'Особые пожелания...',
    'waiter.viewOrder': 'Просмотр заказа',
    'waiter.all': 'Все',
    'waiter.selectItems': 'Выберите позиции',
    'waiter.free': 'Свободен',
    'waiter.active': 'Активен',
    'waiter.served': 'Подан',
    'waiter.preparing': 'Готовится',
    'waiter.logout': 'Выйти',
    'waiter.activeOrders': 'Активные заказы',
    'waiter.noActiveOrders': 'Нет активных заказов для этого стола',
    'waiter.tableCount': 'Количество столов',
    'waiter.settings': 'Настройки',
    'waiter.newOrder': 'Новый',
    'waiter.tableActivity': 'Активность стола',
    'waiter.orderFor': 'Заказ для',
    'waiter.markPaid': 'Отметить оплаченным',
    'waiter.readyBadge': 'Готово!',
    'waiter.addItems': 'Добавить позиции',
    'waiter.payNow': 'Оплатить и закрыть стол',
    'waiter.outstanding': 'К оплате',
    'waiter.waitingPayment': 'Ожидает оплаты',
    'waiter.tableDetails': 'Детали стола',
    'waiter.servedOrders': 'Готовые заказы',
    'waiter.paidSuccess': 'Оплата зарегистрирована!',
    'waiter.selectPayment': 'Выберите способ оплаты',
    'waiter.cash': 'Наличные',
    'waiter.credit': 'Кредитная карта',
    'waiter.appPay': 'Приложение / Перевод',
    'waiter.other': 'Другое',
    'waiter.paymentNote': 'Заметка (необязательно)...',
    'waiter.confirmPayment': 'Подтвердить оплату',
    // Kitchen
    'kitchen.title': 'Кухонный экран',
    'kitchen.new': 'Новые',
    'kitchen.preparing': 'Готовится',
    'kitchen.ready': 'Готово',
    'kitchen.startPreparing': 'Начать готовку',
    'kitchen.markReady': 'Отметить готовым',
    'kitchen.min': 'мин',
    'kitchen.live': 'В эфире',
    'kitchen.offline': 'Не в сети',
    'kitchen.noNewOrders': 'Нет новых заказов',
    'kitchen.noPreparing': 'Ничего не готовится',
    'kitchen.noReady': 'Ничего не готово',
    // Inventory
    'admin.inventory': 'Склад',
    'admin.history': 'История',
    'waiter.addSessionNote': 'Добавить заметку...',
    'waiter.sessionNotePlaceholder': 'Например: аллергия на орехи, день рождения...',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('cafe-nof-language');
    return (saved as Language) || 'he';
  });

  const isRTL = language === 'he' || language === 'ar';

  useEffect(() => {
    localStorage.setItem('cafe-nof-language', language);
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
